app/Dockerfile, app/docker-compose.yml
Added comments to, and made `Dockerfile` less laissez-faire. Added new fields to `prms` service in `docker-compose.yml`.
=> Dockerfile modifications/comments and docker-compose.yml additions

app/Dockerfile
updated `RUN` instructions accordingly.
=> Switched base image from CentOS 7 to Miniconda 3, and:

app/Dockerfile, app/docker-compose.yml, app/nhm
added convenience soft link to `/var/lib/nhm`, and added temporary `sleep infinity` command at end of controller script.
=> Switched onhm-runners repo. reference, added "entrypoint" instruction to ofp service, and:

app/Dockerfile, app/README.md, app/docker-compose.yml, app/nhm, app/ofp, app/ofp.sh
Hey Andy, I've got this mostly working, enough to perhaps run through with you?  Also in my second commit I have a small suggested change to the shapefile check and download.
=> added ofp script

.idea/docker-images.iml, .idea/misc.xml, .idea/modules.xml, .idea/vcs.xml, .idea/workspace.xml, app/Dockerfile, app/cdf2cbh, app/docker-compose.yml, app/ncf2cbh, app/nhm, app/nhm-prms, app/ofp, app/out2ncf, app/verifier
added full list of services.  Some services with entry points crash when running ``` docker-compose up --build``` but ofp remains running and individual services can be called using ```docker exec <service>``` .  Still some things to work out.
=> Added full suite of services

app/nhmusgs-base/Dockerfile
This messes with Jenkins building this image 
https://issues.jenkins-ci.org/browse/JENKINS-44789
https://issues.jenkins-ci.org/browse/JENKINS-44609
https://issues.jenkins-ci.org/browse/JENKINS-31507
=> Remove the "AS" directive in the base image

nhmusgs-ofp/Dockerfile
Andy, I added a few more logging statements the onhm-fetcher-parser and updated the tag.  So I updated the version here from 0.1.3 to 0.1.4
=> added new logging messages to ofp, so updated the version to download

docker-compose.yml, nhmusgs-nhm-restart/Dockerfile
Added new service nhm-restart to docker-compose
=> added new service nhm-restart to update PRMS restart file

compose-test.sh
Added nhm-restart to test-compose pipeline
=> added nhm-restart to compose-test pipeline

nhmusgs-gridmet/Dockerfile
Dockerfile header here messes with automated build job
=> Remove header from Dockerfile

nhmusgs-base/Dockerfile, nhmusgs-data-loader/Dockerfile, nhmusgs-ncf2cbh/Dockerfile, nhmusgs-nhm-out2ncf/Dockerfile, nhmusgs-nhm-prms/Dockerfile, nhmusgs-nhm-prms/nhm-prms, nhmusgs-nhm-restart/Dockerfile, nhmusgs-ofp/Dockerfile, nhmusgs-verifier/Dockerfile
Removed soft-links under /home/nhm. Do not want in production. Added "chgrp -R" command to put objects under /var/lib/nhm in the "nhm" group.
=> Conda dev. environment embedded in Dockerfile to pick up changes to prerequisites, and:

nhmusgs-ncf2cbh/ncf2cbh, nhmusgs-nhm-prms/nhm-prms, nhmusgs-nhm-restart/Dockerfile
nhmusgs-nhm-restart/Dockerfile.
=> Corrections to nhmusgs-ncf2cbh/ncf2cbh, nhmusgs-nhm-prms/nhm-prms, and:

compose-test.sh, docker-compose.yml, nhmusgs-nhm-prms/Dockerfile, nhmusgs-nhm-prms/prms, nhmusgs-ofp/ofp
Andy, I'm not sure all the env override works for now, but otherwise the entire pipeline runs.  Check it out and let me know
=> complete pipeline working, but all env vars for overriding may not work

README.md, nhmusgs-base/nhm.sh, nhmusgs-ncf2cbh/Dockerfile, nhmusgs-ncf2cbh/ncf2cbh, nhmusgs-nhm-out2ncf/Dockerfile, nhmusgs-nhm-out2ncf/out2ncf, nhmusgs-nhm-prms/prms, nhmusgs-verifier/Dockerfile, nhmusgs-verifier/verifier
README file updates/additions, factored-out unnecessary entry-point scripts, and turned off debug option on PRMS entry-point script.
=> Corrected bug in last_simulation_date (), and:

nhmusgs-base/Dockerfile
Hi guys,
This pull request updates the onhm-runners version
=> updated onhm-runners to version 0.1.4

nhmusgs-base/nhm.sh
This reverts commit fe9191c7f08977f2abaeea82be35cc6a25aaca71.
=> Undo 'Added missing slashes to "ls" commands in last_simulation_date ().'

docker-compose.yml, nhmusgs-nhm-prms/prms
nhm-prms service in Docker Compose file and NHM_DRY_RUN conditional message in PRMS entrypoint script.
=> Added DIR, START_DATE, and END_DATE environment variables to:

docker-compose.yml, nhm.env, nhmusgs-nhm-prms/prms, run.sl
Andy,
This ran last night and I believe is working with one exception: The gridmet container is not running correctly with the following output:
Running gridmet...
/opt/conda/bin/python: can't open file 'gridmetetl/gridmetetl/Gridmet_current.py': [Errno 2] No such file or directory, I think it may be that the gridmetetl (the top of the source directory) is only installed in the ofp container and not the volume?  
Sorry I didn't see you pull request until this morning.  Please merge this one first if you can.
=> shifter_gv11 ran to completion, wrote correct restart file

nhmusgs-base/Dockerfile, nhmusgs-ncf2cbh/Dockerfile, nhmusgs-nhm-out2ncf/Dockerfile
Removed obsolete `NUMDAYS` environment variable from ncf2cbh & out2ncf.
=> Updated value of VERSION_ONHM_RUNNERS in base image Dockerfile, and:

nhm.env, nhmusgs-base/Dockerfile, nhmusgs-gridmet/Dockerfile, nhmusgs-ncf2cbh/Dockerfile, nhmusgs-ncf2cbh/ncf2cbh, nhmusgs-ofp/Dockerfile, run.sl
Andy, This repo is well behind conical 1.0.  It has my changes from yesterday to account for datetime issues in gridmetetl, and ncf2cbh, which have new tags.  Also changed ncf2cbh to run from shell script instead of the Docker entrypoint.
=> 1.0 - recent fixes to datetime issues

nhmusgs-base/Dockerfile, nhmusgs-nhm-prms/Dockerfile, nhmusgs-verifier/Dockerfile
Also made wget less noisy by adding `-nv` option.
=> Corrected faults in gridmetetl, PRMS, and onhm-verify-eval source downloading

nhmusgs-cbhfiller/submit.sl, nhmusgs-data-loader/submit.sl, nhmusgs-gridmet-current/submit.sl, nhmusgs-gridmetetl/submit.sl, nhmusgs-nhm-out2ncf/submit.sl, nhmusgs-nhm-prms/submit.sl, nhmusgs-verifier/submit.sl
=> Replaced SOURCE environment variable reference with hard-coded path:

nhmusgs-nhm-prms/Dockerfile
... work around DOI SSL intercept cert. on Red Hat.
=> @ashalper-usgs Added --no-check-certificate option to wget to:

nhmusgs-base/Dockerfile
=> Restored some apt-get install code that was accidentally deleted from:
